version: "3"
services:
  bikerent-postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'user'
      POSTGRES_DATABASE: 'bikerent'
    ports:
      - "5432:5432"
    volumes:
      - .data/postgres:/var/lib/postgresql/data
